packages:
  - "apps/**/*"
  - "libs/**/*"
  - "lab/**/*"
  - "!**/legacy/**"
  - "!**/build"
  - "!**/dist*"
  - "!library/*"
  - "!apps/firebase-functions"
  - "!apps/docs"
catalogs:
  prisma:
    prisma: latest
